name: stngo # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.0.8' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple Timesheet Notation implemented in Golang
description: |
  Golang implementation of Simple Timesheet Notation plus some
  additional utilities and go packages. Included are

  + stnparse - translates a standard input and output turning Simple Timesheet Notation into a tab delimited table with RFC3339 dates or JSON blobs.
  + stnfilter - filters the output of stnparse by dates or text string
  + stnreport - summarizes the tab delimited output of stnfilter or stnparse yielding a simple table showing hours and first annotations

  See https://rsdoiel.github.io/stngo

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  stnparse:
    command: bin/stnparse
    plugs:
      - home
    aliases: [stnparse]
  stnfilter:
    command: bin/stnfilter
    plugs:
      - home
    aliases: [stnfilter]
  stnreport:
    command: bin/stnreport
    plugs:
      - home
    aliases: [stnreport]

parts:
  stngo:
    plugin: go
    go-channel: stable
    build-environment:
        - "CGO_ENABLED" : "0"
    source-type: git
    source: https://github.com/rsdoiel/stngo
